выполняет разметку страниц в файлах
htmlacademy-htmlcss/2127621-sedona-35 pull request #2
Opened 2022-09-23 21:33 UTC by 19Roman87

2022-09-23 23:05 UTC, Ankhena requested changes

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +		<header class="main-header">
Лучше код форматировать "лесенкой", так тебе же самому будет понятнее что происходит. 
![2022-09-24_01-33-47](https://user-images.githubusercontent.com/20879307/192065479-ea226c9f-49a5-4da1-8152-bdcde0ad15a7.jpg)

Форматирование кода доступно в VS Code с помощью следующих сочетаний клавиш:

- В Windows
`Shift +Alt +F`
- На Mac
`Shift + Option +F`
- В Ubuntu
`Ctrl + Shift + I`

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +              <span class="visually-hiden">Вход</span>	<!--скрыть текст и поставить иконку-->
Это вход куда?
Посмотри внимательно на макет, что там нарисовано в этом месте :)

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +        <ul class="navigation-list navigation-user">
Посмотри на макет, подумай, стоит ли давать одинаковые классы элементам и ссылкам в правом и левом меню. Не обязательно принимать это решение сейчас.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +        <img class="main-logo-welcome" src="img/welcome.png" alt="Приглашение">	<!--картинка-->
В этом блоке 3 картинки. 
Горы - фон. 
Зигзаг - фон. 
Слова - единственная контентная картинка.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +              <span class="visually-hiden">Поиск</span>	<!--скрыть текст и поставить иконку-->
Опечатка -> visually-hidden

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +              <span class="visually-hiden">Лайк</span>	<!--скрыть текст и поставить иконку-->
А тут не просто избранное. Тут на макете есть ещё и число, показывающее сколько отелей пользователь уже добавил в избранное. И оно может меняться, а значит, должно быть в разметке.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +			<section class="title">	<!--заголовок-->
Что-то пошло не так
![2022-09-24_01-44-31](https://user-images.githubusercontent.com/20879307/192066208-1a5aa31d-a25b-4cb5-8633-9f1d3e9d19ca.jpg)


И это одна секция, в которой есть заголовок, текст (предложение рассмотреть причины и потом список из самих 5 причин)

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +          <li class="advantages-item">
Жилье-Еда-Сувениры - это отдельный список каких-то дополнительных преимуществ. Просто он идет вплотную к первому. 
Видишь, в 5ти причинах есть полоски у элементов. А у этих 3х иконки.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +            <img class="advantages-image-home" src="img/home.svg" alt="">
Эти иконки - это просто украшения блоков, они не контентные.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +				<button class="main-button" type="button">поиск гостниницы в седоне</button>
Как думаешь, что делает эта "кнопка"?

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +				<form class="main-mail-form" action="https://echo.htmlacademy.ru" method="get">
Знаешь в чем различие методов get и post?

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +          <button class="main-mail-button" type="submit">ПОДПИСАТЬСЯ
Весь текст в разметке пишут по правилам языка страницы. Т.е. предложения начинают с большой буквы, а дальше маленькими.
В капс превращают с помощью css.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +            <span class="visually-hidden">Отправить</span>
А зачем тут нужен скрытый текст?

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +      <section class="footer-socials">
Секциям лучше добавлять заголовки.
Если заголовок не придумать или он кажется избыточным, то это не секция.

2022-09-23 23:05 UTC, Ankhena commented on index.html
> +              <img src="img/vk.png" alt="VK">
Эти картинки - просто украшение ссылок - значит, они идут в стили.

2022-09-23 23:05 UTC, Ankhena commented on index.html
>  <html lang="ru">
Прекрасный валидный код 💯 
Молодец!

2022-09-23 23:05 UTC, Ankhena commented on catalog.html
> +              <img src="img/catalog-home.svg" alt="На главную">
Украшение

2022-09-23 23:05 UTC, Ankhena commented on catalog.html
> +            <a class="breadcrumbs-link"></a>
Вроде в макете был текст внутри ссылки?

2022-09-23 23:05 UTC, Ankhena commented on catalog.html
> +            <button class="button-submit" type="submit">Применить</button>
Отлично, типы у кнопок правильные!

2022-09-23 23:05 UTC, Ankhena commented on catalog.html
> +      <span class="result">Найдено гостиниц:</span>
Как ты тут выбрал span?
И где количество найденных гостиниц?

2022-09-23 23:05 UTC, Ankhena commented on catalog.html
> +            <button class="button-info" type="button">Подробнее</button>
Что делают эти кнопки?

2022-09-23 23:05 UTC, Ankhena commented on catalog.html
> +            <a class="hotel-card-link" href="#">
Тут ты очень правильно сделал картинки у заголовок ссылками. 
Но наверху справа есть кнопочки, меняющие расположение карточек и контента внутри них. 
И в другом отображении может получится что-то типа 
![Седона - вид карточек](https://user-images.githubusercontent.com/20879307/192067494-107bc0ed-9ef1-49d3-b9fe-846e3ed5800e.jpg)
И будет очень неудобно, если это будет одна ссылка. 

Потом, чтобы убрать лишние табы с клавиатуры, можно/нужно будет поставить ссылке с картинки `tabindex="-1"`

2022-09-25 18:08 UTC, 19Roman87 commented on index.html
> +		<header class="main-header">
исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +              <span class="visually-hiden">Вход</span>	<!--скрыть текст и поставить иконку-->
нет описания кнопки, вот сам себе и придумал =)

исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +        <ul class="navigation-list navigation-user">
думаю что нет, так как потом в css все равно будут разные стили.

исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +        <img class="main-logo-welcome" src="img/welcome.png" alt="Приглашение">	<!--картинка-->
ага, зигзаг отдельная картинка под "горами" - эти 2 фона будут добавляться через css. а поверх этого фона - контентная картинка в виде слов.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +              <span class="visually-hiden">Поиск</span>	<!--скрыть текст и поставить иконку-->
исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +              <span class="visually-hiden">Лайк</span>	<!--скрыть текст и поставить иконку-->
исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +			<section class="title">	<!--заголовок-->
поправил секцию.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +          <li class="advantages-item">
выделил в отдельный список, добавил ему отдельный класс.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +            <img class="advantages-image-home" src="img/home.svg" alt="">
убрал.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +				<button class="main-button" type="button">поиск гостниницы в седоне</button>
перенаправит нас на окно с параметрами для выбора гостиницы. подумал так - что ссылкой быть не может, так как мы не переходим на новую страницу.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +				<form class="main-mail-form" action="https://echo.htmlacademy.ru" method="get">
Руководствовался этим определением:

get - Этот метод является одним из самых распространенных и предназначен для получения требуемой информации и передачи данных в адресной строке. Пары «имя=значение» присоединяются в этом случае к адресу после вопросительного знака и разделяются между собой амперсандом (символ &). Удобство использования метода get заключается в том, что адрес со всеми параметрами можно использовать неоднократно, сохранив его, например, в закладки браузера, а также менять значения параметров прямо в адресной строке.

Метод post посылает на сервер данные в запросе браузера. Это позволяет отправлять большее количество данных, чем доступно методу get, поскольку у него установлено ограничение в 4 Кб. Большие объемы данных используются в форумах, почтовых службах, заполнении базы данных, при пересылке файлов и др.

исправил на post - ведь указанный почтовый ящик будет использоваться для пересылки файлов подписавшемуся клиенту.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +          <button class="main-mail-button" type="submit">ПОДПИСАТЬСЯ
text-transform:  uppercase

подумал так - если можно сразу верхним регистром написать - зачем писать отдельное свойство в стилях...

исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +            <span class="visually-hidden">Отправить</span>
это я через чур "пересмотрел" видео - где говорилось про адаптивную верстку сайтов для слабовидящих.

убрал.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +      <section class="footer-socials">
понял, тогда просто <div> ?

исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
> +              <img src="img/vk.png" alt="VK">
исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on index.html
>  <html lang="ru">
спасибо

2022-09-25 18:09 UTC, 19Roman87 commented on catalog.html
> +              <img src="img/catalog-home.svg" alt="На главную">
исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on catalog.html
> +            <a class="breadcrumbs-link"></a>
исправил. (уже начал засыпать =\ )

2022-09-25 18:09 UTC, 19Roman87 commented on catalog.html
> +            <button class="button-submit" type="submit">Применить</button>
спасибо.

2022-09-25 18:09 UTC, 19Roman87 commented on catalog.html
> +      <span class="result">Найдено гостиниц:</span>
думаю стоит поместить в тег <p>, а вот по самой цифре - мне кажется что ее наверное тоже надо отдельно выделить...

исправил.

2022-09-25 18:09 UTC, 19Roman87 commented on catalog.html
> +            <button class="button-info" type="button">Подробнее</button>
сначала подумал что она должна открыть какое то небольшое окно с информацией, возможно контактами...
а мб это будет ссылка на сайт самого отеля...
наверное все же второй вариант.

исправил на ссылки.

2022-09-25 18:09 UTC, 19Roman87 commented on catalog.html
> +            <a class="hotel-card-link" href="#">
тогда думаю лучше убрать вообще ссылку, ведь мы оставляем ссылку на отель при нажатии на "ПОДРОБНЕЕ"

2022-09-25 18:20 UTC, 19Roman87 commented
исправляет замечания

2022-09-25 20:14 UTC, merged